### ISSUE TITLE
Adapter IP bei Verwendung von iobroker in Docker

### ISSUE THREAD

**Issue by nardum** [BuZZy1337/ioBroker.doorbird#19]
Ich habe das Problem, dass der Adapter nicht startet wenn ich als Adapter IP die IP des Hosts eintrage.
![Bildschirmfoto 2022-01-31 um 14 26 44](https://user-images.githubusercontent.com/98751656/151801736-ea239cfb-7a5e-406b-95b9-4cad42eb64e1.png)
Portweitergabe im Docker und Firewallfreigabe sind erteilt.

Hier der Auszug aus dem Log:
2022-01-31 14:22:22.457 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | --
doorbird.0 | 2022-01-31 14:22:22.456 | info | terminating
doorbird.0 | 2022-01-31 14:22:22.446 | error | Exception-Code: EADDRNOTAVAIL: listen EADDRNOTAVAIL: address not available 192.168.1.145:8100
doorbird.0 | 2022-01-31 14:22:22.445 | error | Error: listen EADDRNOTAVAIL: address not available 192.168.1.145:8100 at Server.setupListenHandle [as _listen2] (net.js:1314:21) at listenInCluster (net.js:1379:12) at doListen (net.js:1516:7) at processTicksAndRejections (internal/process/task_queues.js:83:21)
doorbird.0 | 2022-01-31 14:22:22.444 | error | uncaught exception: listen EADDRNOTAVAIL: address not available 192.168.1.145:8100
doorbird.0 | 2022-01-31 14:22:22.400 | info | starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.doorbird, node: v14.18.3, js-controller: 3.3.22

Trage ich als Adapter IP 0.0.0.0 ein, dann startet der Adapter erfolgreich, jedoch werden auch die http-Aufrufe in Doorbird mit 0.0.0.0 generiert und funktionieren dementsprechend nicht.

Hat jemand eine Idee was ich falsch mache?

Besten Dank im Voraus!

**Comment by Nexwarrior** [comment]
Thema ist erledigt. Ich habe dem Container ein MACVLAN zugewiesen und fährt die Instanz erfolgreich hoch.

**Comment by sektoderselters** [comment]
@Nexwarrior 

was genau muss man wo einstellen? Ich habe nämlich das gleiche Problem.
LG

**Comment by nardum** [comment]
Das ist keine kleine Einstellung. Ich habe Docker so konfiguriert das der Docker Container für IO-Broker eine eigenständige IP bekommt. Ich bin nach dieser Anleitung vorgegangen:
https://smarthome.buanet.de/2020/09/macvlan-ueber-portainer-einrichten/

**Comment by mcm1957** [comment]
> Thema ist erledigt. Ich habe dem Container ein MACVLAN zugewiesen und fährt die Instanz erfolgreich hoch.
OK, thanks for info
